
	# Install all packages
	packages <- c(
		'bayesplot',
		'brms',
		'coda',
		'cowplot',
		'data.table',
		'devtools',
		'DHARMa',
		'enmSdmX',
		'ggplot2',
		'ggmcmc',
		'ggnewscale',
		'ggspatial',
		'HDInterval',
		'lmtest',
		'nimble',
		'nimbleHMC',
		'omnibus',
		'openxlsx',
		'patchwork',
		'predicts',
		'sandwich',
		'spdep',
		'statisfactory',
		'terra',
		'viridis',
		'readxl',
		'AICcmodavg',
		'cluster',
		'ggdendro',
		'grid',
		'gridExtra',
		'lme4',
		'MuMIn',
		'tidyr'
	)

	install.packages(packages, lib = 'C:/Kaji/Research/Andropogon/Andropogon/libraries')
